### ISSUE TITLE
Stepper Motor Actuator from Loom3 needs worked into V4

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#10]
Implementation and LoomV4 Max Subscribe example needs made for the Stepper motor
An additional example in the Actuator section just showing how to send a number of steps and speed manually in code would be useful too.
Possible activity for Jace to learn how to integrate Actuators in Loom and Max Subscribe?

**Comment by WL-Richards** [comment]
There is already an implementation for the Stepper motor just without an example

**Comment by udellc** [comment]
Glad to hear, we just need the example then.

**Comment by WL-Richards** [comment]
I just pushed the max example
