### ISSUE TITLE
4G Board not connecting to server

### ISSUE THREAD

**Issue by alexeiaburgos** [OPEnSLab-OSU/Loom-V4#100]
**Describe the bug**
4G Board does not connect to server even with the blue LED flashing. The 4G board initializes and power up but fails to connect to server. 

**Hardware in Use**
Feather M0, Hypnos, New Chime PCB, 4G Board,

**Expected behavior**
4G board connecting to 4G servers 

**Code**
WeatherChimes4G Example Code

**Comment by WL-Richards** [comment]
It's very possible the device was in a spot with bad cell reception cause ATT just kinda sucks

**Comment by WL-Richards** [comment]
Boards were improperly registered with hologram, issue has been resolved.
