### ISSUE TITLE
Need Loom Walkthrough Videos Updated

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#101]
I need someone (please assign someone @WL-Richards ) to update our Loom Dev onboarding videos with the latest content, found here:
Manager/Module:
https://youtu.be/ikSL6U2QvMM

Hot to use Git
https://youtu.be/jRJ6Aklc4iQ

Loom Logger:
https://youtu.be/O3mnjWIp8MI

I2c and i2c MUX:
https://youtu.be/TrAzs9ex4kE

Do we have a hypnos class walkthrough video?

**Comment by WL-Richards** [comment]
These have been merged
