### ISSUE TITLE
Was Hypnos _SD example ever tested? missing manager.initialize();

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#103]
**Describe the bug**
Do we need a manager.initialize(); in setup? If not, why not?

**Hardware in Use**
Just looking at example code

**To Reproduce**
Open Hypnos_SD example under Loom > Hypnos

**Expected behavior**
Do we need a manager.initialize(); in setup? If not, why not?

**Comment by WL-Richards** [comment]
Technically the Hypnos doesn't use the initialize function so we don't need it. However, I have just added it to the main_+ branch for posterity
