### ISSUE TITLE
Integrate these ENGR102 Examples in Board Profile

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#117]
We need these examples included in the next Loom Board Profile!
Please see attached.
These should be located in:
File > Examples > Loom > ClassExamples > E102 > [example here]
[ENGR102.zip](https://github.com/OPEnSLab-OSU/Loom-V4/files/13890391/ENGR102.zip)

**Comment by WL-Richards** [comment]
https://github.com/OPEnSLab-OSU/Loom-V4/pull/118 Approve that pull request for them to be added

**Comment by udellc** [comment]
Approved and merged
