### ISSUE TITLE
Analog Vbat readings spike

### ISSUE THREAD

**Issue by alexeiaburgos** [OPEnSLab-OSU/Loom-V4#130]
**Describe the bug**
The analog reading for Vbat is an accurate. The battery was steadily decreasing at 3.6V and there were certain data packets where the Vbat had spiked to 4.4V.

**Hardware in Use**
WeatherChimes build. Feather-Hypnos stack on Khuti WeatherChimes PCB. Sensors: Tipping bucket, osmopod, SHT31, Teros10, TSL light sensor.

**To Reproduce**
Not sure how to reproduce. Leave running for an extended amount of time?

**Code**
WeatherChimes4GTippingBucket Example

**Output**
See attached
[output_4.log](https://github.com/OPEnSLab-OSU/Loom-V4/files/14306009/output_4.log)
[KhutiChime4.csv](https://github.com/OPEnSLab-OSU/Loom-V4/files/14306010/KhutiChime4.csv)

**Comment by WL-Richards** [comment]
This is likely a non-issue as its probably just switching over to the solar charger which has a higher voltage
