### ISSUE TITLE
Update Doxygen For Hypnos

### ISSUE THREAD

**Issue by ZakaryW** [OPEnSLab-OSU/Loom-V4#132]
Currently the doxygen documentation does not cover the enums that are outside the Hypnos class, but are used within the Hypnos functionality. So to fix this, we need to regenerate the doxygen and ensure it includes these enums.

**Comment by ZakaryW** [comment]
Some extra context,

The config file is located in the root directory of the repo, [Doxyfile](https://github.com/OPEnSLab-OSU/Loom-V4/blob/main/Doxyfile). This is the current [Hypnos Documentation](https://openslab-osu.github.io/Loom-V4/class_loom___hypnos.html), the enums which are in the Hypnos header file aren't documented here so we want to change that. It might be worth looking through Doxygen's documentation for [documenting code](https://www.doxygen.nl/manual/docblocks.html) as well.

**Comment by WL-Richards** [comment]
You will likely have to change some of the directory and file paths in the Doxyfile as they are absolute paths on my machine

**Comment by udellc** [comment]
@ZakaryW , where are we at with this? Can we finish up and close this out?

**Comment by udellc** [comment]
Not a high priority though

**Comment by WL-Richards** [comment]
closing for now, can re-address later
