### ISSUE TITLE
Figure out MS5803 initialization weirdness

### ISSUE THREAD

**Issue by WL-Richards** [OPEnSLab-OSU/Loom-V4#150]

**Comment by udellc** [comment]
We neet to re-test after we updated the library to see if this is still an issue.

**Comment by udellc** [comment]
Let's stablize this so we can rely on the CRC checks!

**Comment by mbelinga777** [comment]
Hi @udellc 
After updating the library like will suggested, I conducted tests on five MS5803 sensors. Four of the sensors passed the CRC checks consistently, but one failed despite the data appearing accurate. It seems the issue with the failing sensor could be hardware-related.
It looks like the library update has improved overall stability regarding the CRC checks, but the single failing sensor may need further investigation.
Let me know if additional testing or troubleshooting is required.

**Comment by udellc** [comment]
Thanks for the update @mbelinga777 !
@WL-Richards , can we be sure the updated MS5803 library is pushed to the main branch? Then close the issue?

**Comment by WL-Richards** [comment]
Since this a non-Loom library it doesn't actually get pushed to main it just gets updated in the board profile

**Comment by natashazai** [comment]
After updating the MS5803 library and uncommenting the code for MS5803.cpp, it initializes both osmopods now. Data is being read properly.
<img width="1728" alt="Screen Shot 2024-10-02 at 10 57 08 AM" src="https://github.com/user-attachments/assets/c48542d1-2e9d-4722-b82b-28b3ae61dd63">

**Comment by natashazai** [comment]
When there is only one osmopod connected, so the one that is on the board, it properly fails to initialize one of them as it should be
<img width="1411" alt="Screen Shot 2024-10-02 at 11 11 07 AM" src="https://github.com/user-attachments/assets/fb5a64dc-2cfa-4b8c-91d2-4e7785793b24">

**Comment by natashazai** [comment]
All osmopods were tested
