### ISSUE TITLE
Integrate the i2c VCNL 4010 Optical Sensor for Smart Rock Turbidity

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#156]
Looks like a standard i2c sensor integration: Integrate the i2c VCNL 4010 Optical Sensor for Smart Rock Turbidity.

Start with dirty integration of example code, place data into Loom packet manually.

Then integrate into Loom, i2c Modules

**Comment by WL-Richards** [comment]
[SR_prox_turb_test2.txt](https://github.com/user-attachments/files/17347691/SR_prox_turb_test2.txt)
Example code in here

**Comment by WL-Richards** [comment]
In progress

**Comment by WL-Richards** [comment]
Soren is now in charge of testing and cleaning up the remaining code to take some stuff off Natasha's plate

**Comment by SorenEmmons** [comment]
I cleaned it up and it does compile on Arduino, but it needs to be tested with the sensor itself.

**Comment by WL-Richards** [comment]
Fixed
