### ISSUE TITLE
Time local should not have the 'Z' suffix (ISO_8601)

### ISSUE THREAD

**Issue by sarveshta** [OPEnSLab-OSU/Loom-V4#165]
The Z suffix is supposed to indicate Zulu time (military/aviation term for UTC) per [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)) and should not be included in the time_local part of the output.

Example: 

> 11:44:57.707 ->   "timestamp": {
> 11:44:57.707 ->     "time_utc": "2024-11-02T19:44:12Z",
> 11:44:57.707 ->     "time_local": "**2024-11-02T10:44:12Z**"
> 11:44:57.707 ->   }

**Comment by WL-Richards** [comment]
This has been fixed in 4.7-merge

**Comment by WL-Richards** [comment]
Removed as per 4.7-merge
