### ISSUE TITLE
Rewording hypnos.sleep(false);

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#18]
In the finction: hypnos.sleep(false);
It appears to read that we are negating or bypassing the functionality. Is it possible to modify the parameters to make 
hypnos.sleep(); 
the commonly used format, and to assign flags to enable or disable features in a way that reads more intuitively?

**Comment by WL-Richards** [comment]
Just delete the false and it will have the same behavior
