### ISSUE TITLE
Evaporometer example code not working

### ISSUE THREAD

**Issue by jamopopper** [OPEnSLab-OSU/Loom-V4#2]
Evaporometer code initializes everything successfully but does not write to SD nor output json data to serial. If starts up every 30 seconds but does not write.

**Comment by WL-Richards** [comment]
It should use the proper beginSerial call now I would try again with hardware, if you can see the serial output it should give you more information as to what is going wrong

**Comment by jamopopper** [comment]
Implemented power_up and power_down, along with setting pins. Evaporometer code works properly
