### ISSUE TITLE
Spaces in JSON labels need replaced with underscore

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#21]
Spaces in names in JSON labeleing of sensor data can create parsing errors where spaces are not allowed in certain applications, Max right now, but likely in other apps too.
Go through all labels and replace spaces with _ underscore please!

**Comment by WL-Richards** [comment]
That is a horrible JSON parser if spaces cause issues, its an isolated key

**Comment by WL-Richards** [comment]
It has been fixed....

**Comment by udellc** [comment]
Thanks Will! Maybe we can look at the parser in in the Max Javascript to see why it's dumb like that.
