### ISSUE TITLE
Loom_Hypnos cpp has RTC interrupt pin hard coded in places

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#22]
In the Loom_Hypnos.cpp, it appears the interrupt pin assignment for functions are hard coded to pin 12.
For example:
void Loom_Hypnos::wakeup(){
    detachInterrupt(digitalPinToInterrupt(12));     // Detach the interrupt so it doesn't trigger again    
}

And yet, Hypnos RTC functionality seems to work even though Loom_Hypnos.h has 
 V3_2 = 10,
    V3_3 = 11

Any ideas why this is the case?

**Comment by WL-Richards** [comment]
The V3_2 and V3_3 are the SD chip select as for the other one I am working on getting it moved over

**Comment by WL-Richards** [comment]
I have altered the interrupt to detach to be equal to the pin of the first scheduled interrupt
