### ISSUE TITLE
Hypnos Adalogger SD CS pin typo

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#24]
In Hypnos header file, Adalogger CS pin needs to be 4, not 5:
enum HYPNOS_VERSION{
    V3_2 = 10,
    V3_3 = 11,
    ADALOGGER = 4
};

**Comment by WL-Richards** [comment]
You told me 5 in the meeting but it has been fixed

**Comment by udellc** [comment]
Still not fixed in the hypnos h file, still says 5

**Comment by WL-Richards** [comment]
It's in the other Hypnos branch
