### ISSUE TITLE
ADS1115 not giving expected values for analog readings?

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#25]
**Describe the bug**
ADS1115 Code does not report ADC values we expect to receive. Seems some bits are truncated, possibly the data type used to store this data is not correct? ADS1115 is a 16-bit ADC, but gives a data range of 15 bits 0 - 2^15. Because the 16th bit is a sign but used for an alternative mode we don't typically use on the ADS1115 chip called differential mode.
This is bad because the ADS1115 is of many projects: SmartRock, LilyPad, to name some.

** It is unclear if this is a Loom issue, a library issue with the 1115, or something in hardware.

**Hardware in Use**
Feather M0, ADS1115. then use the SmartRock board

**What we need to do**
A simple ADS1115 breakout on a breadboard with a feather M0.
Set up a linear trim potentiometer on the breadboard, with one side on VCC, the other side GND, and the middle pin going to the Analog input channel on the ADS1115. 
Turn the trip pot all the way to one side, the middle, then the other side. Observe Voltage output on the Osciloscope and the ADS1115 data output in the serial monitor. 
Make a table of observed values and post.

Prove if values make sense or not with breadboard basic hardware, then we need to test with the SmartRock board.

**Comment by WL-Richards** [comment]
Should be using a full size integer now
