### ISSUE TITLE
Check Loom4 Analog module 12-bit mode!

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#3]
The M0 SAMD21 has 12-bit analog ADC pins, but Arduino sets these to 10-bit by default, more normally seen.
We need to *Explicitly* tell the M0 to set the ADC to 12-bit mode. This was done in older version of Loom, but not seen in the V4 code.
// Set Analog Read Resolution
	analogReadResolution(read_resolution);
read-resolution should be set to 12 by default

**Comment by WL-Richards** [comment]
Updated to use 12-bit resolution
