### ISSUE TITLE
Adding mV calculation to Analog module; Teros 10 sensor calculation support

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#36]
We will need to add into the Arduino code for WeatherChimes how to calculate Dialectic Permittivity and perhaps Volumetric Water Content in addition to the raw analog values, and pack them into the Loom packet. The datasheet to find these formulas is here: http://publications.metergroup.com/Manuals/20788_TEROS10_Manual_Web.pdf

Equation 6 is Dialec Perm and Equation 2 is VWC

Note - we need to calculate **millivolts first** from the ADC reading. We are doing this with internal functions in the ADS1115 when using that, but we are using the A0 port on the M0 instead, so in Loom, we ought to calculate mV and log it automatically so we can pull this value if needed. You can convert ADC value to millivolts with these easy equations here:

https://learn.sparkfun.com/tutorials/analog-to-digital-conversion/relating-adc-value-to-voltage

**Comment by WL-Richards** [comment]
Pushed to integration-hell while awaiting testing
