### ISSUE TITLE
Teros10 computeDP formula needs fixed to this:

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#40]
Change formula to this:
float Loom_Teros10::computeDP(float mV){
    return ((1.054 * pow(10, -1)) * exp(2.827 * pow(10, -3) * mV));
}

Used to be this:
float Loom_Teros10::computeDP(float mV){
    return ((1.054 * pow(10, -1)) - exp((2.827) * pow(10, -3) * mV));
}

**Comment by udellc** [comment]
Bump, from formula 6 on this datasheet:
http://publications.metergroup.com/Manuals/20788_TEROS10_Manual_Web.pdf

**Comment by jamopopper** [comment]
Will has made this change
