### ISSUE TITLE
Loom Testing: i2c Need to double check NAK recovery for all sensors

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#41]
If an i2c sensor experiences an outage or malfunction in the field, it could hang the entire system. We need to test commonly used i2c sensors soon, if not all of them on Loom eventually, for recovery if unplugged during operation.

**Comment by udellc** [comment]
@jamopopper , can you run a test on a few random i2c sensors to confirm? 
Initialize and run with a few i2c sensors attached; confirm logging; then remove sensors mid-operation in between sample cycles and see if program hangs.

**Comment by jamopopper** [comment]
Can confirm it works when using multiple sensors and unplugging wires on either and both sensors.
