### ISSUE TITLE
Possible breaking change: 2 MS5803 sensors i2c

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#44]
Pulled the main 9/30/22 at 4pm.
using two MS5803 sensors worked in version before in integration hell branch. 
Possible changes to i2c NAK failing gracefully may have caused break in the two MS5803 0x118 snd 0x119 functionality. 
Shows both MS5803s initializing, but only one reports, does not say which one.

Tested in Weatherchimes code below:
<pre>
<font color="#95a5a6">&#47;**</font>
<font color="#95a5a6"> * In lab use case example for the WeatherChimes project</font>
<font color="#95a5a6"> * </font>
<font color="#95a5a6"> * This project uses SDI12, TSL2591 and an SHT31 sensor to log environment data and logs it to both the SD card and also MQTT&#47;MongoDB</font>
<font color="#95a5a6"> * </font>
<font color="#95a5a6"> * MANAGER MUST BE INCLUDED FIRST IN ALL CODE</font>
<font color="#95a5a6"> *&#47;</font>
<font color="#5e6d03">#include</font> <font color="#005c5f">&#34;arduino_secrets.h&#34;</font>

<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Loom_Manager</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>

<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Hardware</font><font color="#434f54">&#47;</font><font color="#000000">Loom_Hypnos</font><font color="#434f54">&#47;</font><font color="#000000">Loom_Hypnos</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>

<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Sensors</font><font color="#434f54">&#47;</font><font color="#000000">Loom_Analog</font><font color="#434f54">&#47;</font><font color="#000000">Loom_Analog</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Sensors</font><font color="#434f54">&#47;</font><font color="#000000">I2C</font><font color="#434f54">&#47;</font><font color="#000000">Loom_SHT31</font><font color="#434f54">&#47;</font><font color="#000000">Loom_SHT31</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Sensors</font><font color="#434f54">&#47;</font><font color="#000000">I2C</font><font color="#434f54">&#47;</font><font color="#000000">Loom_TSL2591</font><font color="#434f54">&#47;</font><font color="#000000">Loom_TSL2591</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Sensors</font><font color="#434f54">&#47;</font><font color="#000000">I2C</font><font color="#434f54">&#47;</font><font color="#000000">Loom_MS5803</font><font color="#434f54">&#47;</font><font color="#000000">Loom_MS5803</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#434f54">&#47;&#47; If using Teros 10, Uncoment this line</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Sensors</font><font color="#434f54">&#47;</font><font color="#000000">Analog</font><font color="#434f54">&#47;</font><font color="#000000">Loom_Teros10</font><font color="#434f54">&#47;</font><font color="#000000">Loom_Teros10</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>

<font color="#434f54">&#47;&#47; If using SDI12, GS3 or Teros 11 or 12 uncoment this line</font>
<font color="#434f54">&#47;&#47;#include &lt;Sensors&#47;SDI12&#47;Loom_SDI12&#47;Loom_SDI12.h&gt;</font>

<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Internet</font><font color="#434f54">&#47;</font><font color="#000000">Logging</font><font color="#434f54">&#47;</font><font color="#000000">Loom_MQTT</font><font color="#434f54">&#47;</font><font color="#000000">Loom_MQTT</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Internet</font><font color="#434f54">&#47;</font><font color="#000000">Connectivity</font><font color="#434f54">&#47;</font><font color="#000000">Loom_LTE</font><font color="#434f54">&#47;</font><font color="#000000">Loom_LTE</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>

<font color="#000000">Manager</font> <font color="#000000">manager</font><font color="#000000">(</font><font color="#005c5f">&#34;4Gchime&#34;</font><font color="#434f54">,</font> <font color="#000000">10</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">&#47;&#47; Create a new Hypnos object</font>
<font color="#000000">Loom_Hypnos</font> <font color="#000000">hypnos</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">HYPNOS_VERSION</font><font color="#434f54">:</font><font color="#434f54">:</font><font color="#000000">V3_3</font><font color="#434f54">,</font> <font color="#000000">TIME_ZONE</font><font color="#434f54">:</font><font color="#434f54">:</font><font color="#000000">PST</font><font color="#434f54">,</font> <font color="#00979c">true</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#434f54">&#47;&#47; Analog for reading battery voltage</font>
<font color="#000000">Loom_Analog</font> <font color="#000000">analog</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">&#47;&#47; Create sensor classes</font>
<font color="#000000">Loom_SHT31</font> <font color="#000000">sht</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">Loom_TSL2591</font> <font color="#000000">tsl</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">Loom_MS5803</font> <font color="#000000">ms_water</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">119</font><font color="#000000">)</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; 119(0x77) if CSB=LOW external, 118(0x76) if CSB=HIGH on WC PCB</font>
<font color="#000000">Loom_MS5803</font> <font color="#000000">ms_air</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">118</font><font color="#000000">)</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; 118(0x76) if CSB=HIGH on WC PCB</font>

<font color="#000000">Loom_LTE</font> <font color="#000000">lte</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">NETWORK_APN</font><font color="#434f54">,</font> <font color="#000000">NETWORK_USER</font><font color="#434f54">,</font> <font color="#000000">NETWORK_PASS</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">Loom_MQTT</font> <font color="#000000">mqtt</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">lte</font><font color="#434f54">.</font><font color="#000000">getClient</font><font color="#000000">(</font><font color="#000000">)</font><font color="#434f54">,</font> <font color="#000000">SECRET_BROKER</font><font color="#434f54">,</font> <font color="#000000">SECRET_PORT</font><font color="#434f54">,</font> <font color="#000000">DATABASE</font><font color="#434f54">,</font> <font color="#000000">BROKER_USER</font><font color="#434f54">,</font> <font color="#000000">BROKER_PASS</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">&#47;&#47; If using Teros 10, Uncoment this line</font>
<font color="#000000">Loom_Teros10</font> <font color="#000000">t10</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">A2</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">&#47;&#47; If using SDI12, GS3 or Teros 11 or 12 uncoment this line</font>
<font color="#434f54">&#47;&#47;Loom_SDI12 sdi(manager, A2);</font>

<font color="#434f54">&#47;&#47; Called when the interrupt is triggered </font>
<font color="#00979c">void</font> <font color="#000000">isrTrigger</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">{</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#000000">wakeup</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">}</font>

<font color="#00979c">void</font> <font color="#5e6d03">setup</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>

 &nbsp;<font color="#434f54">&#47;&#47; Wait 20 seconds for the serial console to open</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">beginSerial</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#434f54">&#47;&#47; Enable the hypnos rails</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#d35400">enable</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#434f54">&#47;&#47; Initialize all in-use modules</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">initialize</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#434f54">&#47;&#47; Register the ISR and attach to the interrupt</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#d35400">registerInterrupt</font><font color="#000000">(</font><font color="#000000">isrTrigger</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">}</font>

<font color="#00979c">void</font> <font color="#5e6d03">loop</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>

 &nbsp;<font color="#434f54">&#47;&#47; Measure and package the data</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">measure</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">package</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;
 &nbsp;<font color="#434f54">&#47;&#47; Print the current JSON packet</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">display_data</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

 &nbsp;<font color="#434f54">&#47;&#47; Log the data to the SD card &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#000000">logToSD</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#434f54">&#47;&#47; Publish the collected data to MQTT</font>
 &nbsp;<font color="#000000">mqtt</font><font color="#434f54">.</font><font color="#000000">publish</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#434f54">&#47;&#47; &nbsp;manager.pause(5000);</font>

 &nbsp;<font color="#434f54">&#47;&#47; Set the RTC interrupt alarm to wake the device in 15 min</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#000000">setInterruptDuration</font><font color="#000000">(</font><font color="#000000">TimeSpan</font><font color="#000000">(</font><font color="#000000">0</font><font color="#434f54">,</font> <font color="#000000">0</font><font color="#434f54">,</font> <font color="#000000">15</font><font color="#434f54">,</font> <font color="#000000">0</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#434f54">&#47;&#47; Reattach to the interrupt after we have set the alarm so we can have repeat triggers</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#000000">reattachRTCInterrupt</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;
 &nbsp;<font color="#434f54">&#47;&#47; Put the device into a deep sleep, operation HALTS here until the interrupt is triggered</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#d35400">sleep</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;
<font color="#000000">}</font>

</pre>

Serial print:
[SD Manager] Initializing SD Card...
[SD Manager] Successfully initialized SD Card!
[SD Manager] Data will be logged to 4Gchime17.csv
[Hypnos] DS3231 Real-Time Clock Initialized Successfully!
[Manager] Initializing Modules...
[SHT31] Successfully initialized SHT31!
[TSL2591] Successfully initialized TSL2591!
[MS5803] Successfully Initialized!
[MS5803] Successfully Initialized!
[LTE] Powering up GPRS Modem. This should take about 10 seconds...
[LTE] Powering up complete!
[LTE] Modem Information: Manufacturer: u-blox Model: SARA-R410M-02B Revision: L0.0.00.00.05.08 [Apr 17 2019 19:34:02] SVN: 03 IMEI: 355523760070757
[LTE] Waiting for network...
[LTE] Connected to network!
[LTE] Attempting to connect to LTE Network: hologram
[LTE] Successfully Connected!
[LTE] Connected!
[LTE] APN: hologram
[LTE] Signal State: 99
[LTE] IP Address: 100.71.133.128
[LTE] Attempting to verify internet connection...
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Fri, 30 Sep 2022 23:39:23 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 121
Connection: close
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With
Cross-Origin-Resource-Policy: cross-origin
Accept-Ranges: bytes
Cache-Control: public, max-age=86400
Last-Modified: Wed, 27 Sep 2017 09:03:12 GMT
ETag: W/"79-15ec2936080"

  _____            _____  _____  _____
    |  | |\ | \_/ |  ___ |_____ |  |  |
    |  | | \|  |  |_____| _____||  |  |

[LTE] Module successfully initialized!
[Manager] ** Setup Complete ** 
[Hypnos] Registering RTC interrupt...
[Hypnos] Interrupt successfully attached!

[Manager] Data Json: 
{
  "type": "data",
  "id": {
    "name": "4Gchime",
    "instance": 10
  },
  "contents": [
    {
      "module": "Packet",
      "data": {
        "Number": 1
      }
    },
    {
      "module": "Analog",
      "data": {
        "Vbat": 4.368310452,
        "Vbat_MV": 4347.363281
      }
    },
    {
      "module": "SHT31",
      "data": {
        "Temperature": 23.89999962,
        "Humidity": 55.52000046
      }
    },
    {
      "module": "TSL2591",
      "data": {
        "Visible": 530,
        "Infrared": 500,
        "Full_Spectrum": 1031
      }
    },
    {
      "module": "MS5803",
      "data": {
        "Temperature": 25.43000031,
        "Pressure": 1006.280029
      }
    },
    {
      "module": "LTE",
      "data": {
        "RSSI": 23
      }
    },
    {
      "module": "Teros 10",
      "data": {
        "Millivolt_Reading": 845.3480225,
        "Dielectric_Permittivity": 1.150050879,
        "Volumetric_Water_Content": -0.195306107
      }
    }
  ],
  "timestamp": {
    "time_utc": "2022-09-30 23:39:33",
    "time_local": "2022-09-30 16:39:33"
  }
}

[SD Manager] Successfully logged data to 4Gchime17.csv
[MQTT] Creating new MQTT client!
[MQTT] Attempting to connect to broker: cas-mosquitto.biossys.oregonstate.edu:1883
[MQTT] Successfully connected to broker!
[MQTT] Attempting to send data...
[MQTT] Data has been successfully sent!
[Hypnos] Current Time: 2022.09.30 16:39:39
[Hypnos] Next Interrupt Alarm Set For: 2022.09.30 16:54:39
[Hypnos] Interrupt successfully reattached!
[LTE] Powering down GPRS Modem. This should take about 5 seconds...
[LTE] Powering down complete!
[Hypnos] Entering Standby Sleep...

**Comment by jamopopper** [comment]
Do you know what version and branch you were using when it did work? The commit ID would be great, but branch and/or time you pulled previously works too @udellc

**Comment by udellc** [comment]
I used Will's push to Main he did on Friday during our Loom meeting.

**Comment by udellc** [comment]
Not sure if any progress has been made. Just pulled from Main again just now and still not getting both sensors. Maybe code to fix was reverted? Because it is behaving like last time.

[SD Manager] Initializing SD Card...
[SD Manager] Failed to Initialize SD Card! SD Card functionality will be disabled, is there an SD card inserted into the device?
[Hypnos] DS3231 Real-Time Clock Initialized Successfully!
[Manager] Initializing Modules...
[MS5803] Successfully Initialized!
[MS5803] Successfully Initialized!
[Manager] ** Setup Complete ** 
[Hypnos] Registering RTC interrupt...
[Hypnos] Interrupt successfully attached!

[Manager] Data Json: 
{
  "type": "data",
  "id": {
    "name": "WC_MS_test",
    "instance": 1
  },
  "contents": [
    {
      "module": "Packet",
      "data": {
        "Number": 1
      }
    },
    {
      "module": "MS5803",
      "data": {
        "Temperature": 24.77000046,
        "Pressure": 1007.190002
      }
    }
  ],
  "timestamp": {
    "time_utc": "2022-10-07 0:7:44",
    "time_local": "2022-10-06 17:7:44"
  }
}


[Manager] Data Json: 
{
  "type": "data",
  "id": {
    "name": "WC_MS_test",
    "instance": 1
  },
  "contents": [
    {
      "module": "Packet",
      "data": {
        "Number": 2
      }
    },
    {
      "module": "MS5803",
      "data": {
        "Temperature": 24.76000023,
        "Pressure": 1007.169983
      }
    }
  ],
  "timestamp": {
    "time_utc": "2022-10-07 0:7:51",
    "time_local": "2022-10-06 17:7:51"
  }
}



<pre>

<font color="#95a5a6">&#47;**</font>
<font color="#95a5a6"> * In lab test example of using 2 MS5803 sensors each set to different address</font>
<font color="#95a5a6"> * </font>
<font color="#95a5a6"> * This project uses a hypnos, MS5803 with CBS pin on GND and another MS5803 with CBS pin on VCC</font>
<font color="#95a5a6"> * Calculate Water Height using difference of 2 pressure sensors and formulas from:</font>
<font color="#95a5a6"> * </font><u><font color="#95a5a6">https:&#47;&#47;byjus.com&#47;water-pressure-formula&#47;</font></u><font color="#95a5a6"></font>
<font color="#95a5a6"> * (Pwater-Pair)&#47;0.0981 = water height in millimeters</font>
<font color="#95a5a6"> * Convert millibar into Pascals: 1Pa = 0.01 millibar</font>
<font color="#95a5a6"> * </font><u><font color="#95a5a6">https:&#47;&#47;www.unitconverters.net&#47;pressure&#47;pascal-to-millibar.htm</font></u><font color="#95a5a6"></font>
<font color="#95a5a6"> * MANAGER MUST BE INCLUDED FIRST IN ALL CODE</font>
<font color="#95a5a6"> *&#47;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Loom_Manager</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#434f54">&#47;&#47;#include &lt;Wire.h&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Hardware</font><font color="#434f54">&#47;</font><font color="#000000">Loom_Hypnos</font><font color="#434f54">&#47;</font><font color="#000000">Loom_Hypnos</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">Sensors</font><font color="#434f54">&#47;</font><font color="#000000">I2C</font><font color="#434f54">&#47;</font><font color="#000000">Loom_MS5803</font><font color="#434f54">&#47;</font><font color="#000000">Loom_MS5803</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>

<font color="#00979c">float</font> <font color="#000000">height</font> <font color="#434f54">=</font> <font color="#000000">0</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; in millimeters</font>
<font color="#00979c">float</font> <font color="#000000">coeficient</font> <font color="#434f54">=</font> <font color="#000000">10.1936</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; take reciprocal of 0.0981 so we can multiply instead of divide &nbsp;(100mBar * 1000mm) &#47; (1000kg.over.metercube * 9.81meterspersecondsquare)</font>
<font color="#00979c">float</font> <font color="#000000">Pw</font> <font color="#434f54">=</font> <font color="#000000">1</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; Pressure water in millibar</font>
<font color="#00979c">float</font> <font color="#000000">Pa</font> <font color="#434f54">=</font> <font color="#000000">1</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; Pressure air in millibar</font>

<font color="#000000">Manager</font> <font color="#000000">manager</font><font color="#000000">(</font><font color="#005c5f">&#34;WC_MS_test&#34;</font><font color="#434f54">,</font> <font color="#000000">1</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">&#47;&#47; Create a new Hypnos object</font>
<font color="#000000">Loom_Hypnos</font> <font color="#000000">hypnos</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">HYPNOS_VERSION</font><font color="#434f54">:</font><font color="#434f54">:</font><font color="#000000">V3_3</font><font color="#434f54">,</font> <font color="#000000">TIME_ZONE</font><font color="#434f54">:</font><font color="#434f54">:</font><font color="#000000">PST</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">&#47;&#47; Sensors to use</font>
<font color="#434f54">&#47;&#47; Pressure of Water</font>
<font color="#000000">Loom_MS5803</font> <font color="#000000">ms77</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">119</font><font color="#000000">)</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; MS5803 CSB pin pulled GND i2c addr 0x77</font>

<font color="#434f54">&#47;&#47; Pressure of Air</font>
<font color="#000000">Loom_MS5803</font> <font color="#000000">ms76</font><font color="#000000">(</font><font color="#000000">manager</font><font color="#434f54">,</font> <font color="#000000">118</font><font color="#000000">)</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; MS5803 CSB pin pulled VCC i2c addr 0x76</font>

<font color="#434f54">&#47;&#47; Might be desirable to pull sleep interval from SD card, not relevant to sketch, disregard</font>
<font color="#434f54">&#47;&#47;TimeSpan sleepInterval; &#47;&#47; Sleep interval pulled from JSON file on SD Card, see setup</font>

<font color="#434f54">&#47;&#47; ISR not used in loop, no sleep in use</font>
<font color="#434f54">&#47;&#47; Called when the interrupt is triggered </font>
<font color="#00979c">void</font> <font color="#000000">isrTrigger</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">{</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#000000">wakeup</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">}</font>

<font color="#00979c">void</font> <font color="#5e6d03">setup</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>

 &nbsp;<font color="#434f54">&#47;&#47; Wait 20 seconds for the serial console to open</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">beginSerial</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#434f54">&#47;&#47; Enable the hypnos rails</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#d35400">enable</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">initialize</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">&#47;&#47; &nbsp;sleepInterval = hypnos.getSleepIntervalFromSD(&#34;SD_config.json&#34;);</font>
 &nbsp;<font color="#434f54">&#47;&#47; Register the ISR and attach to the interrupt</font>
 &nbsp;<font color="#000000">hypnos</font><font color="#434f54">.</font><font color="#d35400">registerInterrupt</font><font color="#000000">(</font><font color="#000000">isrTrigger</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">}</font>

<font color="#00979c">void</font> <font color="#5e6d03">loop</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>

 &nbsp;<font color="#434f54">&#47;&#47; Measure and package the data</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">measure</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">package</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#95a5a6">&#47;*</font>
<font color="#95a5a6"> &nbsp;&#47;&#47; Calculate water height</font>
<font color="#95a5a6"> &nbsp;Pw = ms77.getPressure();</font>
<font color="#95a5a6"> &nbsp;Pa = ms76.getPressure();</font>
<font color="#95a5a6"> &nbsp;height = (Pw-Pa)*coeficient;</font>
<font color="#95a5a6"></font>
<font color="#95a5a6"> &nbsp;&#47;&#47; Add height to the package</font>
<font color="#95a5a6"> &nbsp;manager.addData(&#34;MS5803both&#34;, &#34;WaterHeight_mm&#34;, height);</font>
<font color="#95a5a6">*&#47;</font>
 &nbsp;<font color="#434f54">&#47;&#47; Print the current JSON packet</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">display_data</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

 &nbsp;<font color="#434f54">&#47;&#47; Log the data to the SD card &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font>
<font color="#434f54">&#47;&#47; &nbsp;hypnos.logToSD();</font>
 &nbsp;<font color="#000000">manager</font><font color="#434f54">.</font><font color="#000000">pause</font><font color="#000000">(</font><font color="#000000">5000</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#434f54">&#47;&#47; If Using Sleep, uncomment:</font>

 &nbsp;<font color="#434f54">&#47;&#47; Set the RTC interrupt alarm to wake the device in 10 seconds</font>
 &nbsp;<font color="#434f54">&#47;&#47;hypnos.setInterruptDuration(sleepInterval); &#47;&#47; if using sd card sleep interval</font>
<font color="#434f54">&#47;&#47; &nbsp;hypnos.setInterruptDuration(TimeSpan(0, 0, 0, 10)); &#47;&#47; if not using sd card sleep interval</font>

 &nbsp;<font color="#434f54">&#47;&#47; Reattach to the interrupt after we have set the alarm so we can have repeat triggers</font>
<font color="#434f54">&#47;&#47; &nbsp;hypnos.reattachRTCInterrupt();</font>
 &nbsp;
 &nbsp;<font color="#434f54">&#47;&#47; Put the device into a deep sleep, operation HALTS here until the interrupt is triggered</font>
<font color="#434f54">&#47;&#47; &nbsp;hypnos.sleep(false);</font>

<font color="#000000">}</font>

</pre>

**Comment by WL-Richards** [comment]
Fixed
