### ISSUE TITLE
Loom V4 Digital values don't change

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#5]
The values on the Digital pins don't change state from 0.
I am using a button that is normally disconnected. one side going to ground, the other to Digital Pin 10. 
I need Loom4 to enable INPUT_PULLUP. I think this is not being done by Loom.

When I manually specify pinMode(10, INPUT_PULLUP);
in the SETUP, the readings function properly. Let's look at how Loom3 handled Digital pin declarations (input, input pullup, output)

**Comment by WL-Richards** [comment]
I didn't see they were using INPUT_PULLUP, its been fixed
