### ISSUE TITLE
Loom Max Servo error

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#51]
In the Loom Max Servo example,
I can set the value to set the servo position from Max, and I get feedback from the Loom device that the servo value was set by looking at the sensor module in Max, which indicates the new servo position. 
But the servo itself does not move.
I do not think we are calling Dispatch to actually tell the servo to go to the target position, or there is an error in that worksflow somewhere.

**Comment by WL-Richards** [comment]
I believe this breaking was an artifact of adding the WiFi Flash storage, likely fix pushed closing for now
