### ISSUE TITLE
K30 reinit after disconnect

### ISSUE THREAD

**Issue by jamopopper** [OPEnSLab-OSU/Loom-V4#56]
K30 fails to reinitialize after being unplugged and replugged. Using git pull version c084462

**Comment by WL-Richards** [comment]
Cleaned up and removed the serial part of the K30, probably didn't fix it but will give us less to dig through

**Comment by udellc** [comment]
This should be assigned to EvanH

**Comment by udellc** [comment]
@hockerte

**Comment by hockerte** [comment]
tested, appears working. K30 re-inits after disconnecting and reconnecting power.

**Comment by udellc** [comment]
What was the fix? Cleaning up and removing Serial?
