### ISSUE TITLE
Urgent, LoRa packet size fix from Loom3 is not implemented in Loom4, but needed

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#59]
Radiohead library for LoRa has a packet limit size for how long data transmissions can be. No way around it it seems (could be wrong). This was fixed in Loom3 by splitting data packets on the transmission side, and reassembling on the hub side. Took a long time for Adam to figure out. We will need this very soon. Please work with Connor to test a fix for this in Loom4!

**Comment by WL-Richards** [comment]
This is kinda a dupe issue of the invalid MsgPack

**Comment by WL-Richards** [comment]
It theoretically should be implemented and just needs to be tested

**Comment by WL-Richards** [comment]
See Version 4.2 
https://github.com/OPEnSLab-OSU/Loom-V4/releases/tag/v4.2
