### ISSUE TITLE
LTE shield error message not helpful if not connected or not SIM card

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#60]
LET shield gives a misleading error message if properly connected and powered on, but no SIM card:
13:07:22.492 -> [LTE] Powering up complete!

13:07:23.503 -> [LTE] LTE Shield not present!

We need a way to know if the shield is not working because if it not attached correctly / powered on - versus it is attached okay but no SIM. Something Loom side should clarify

**Comment by WL-Richards** [comment]
Updated the message to tell the user to check the sim card
