### ISSUE TITLE
Expanding LoRa Range via new library

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#62]
Let's look into evaluating this library on some FeatherM0 LoRa boards to see if we get better performance:
https://github.com/mcci-catena/arduino-lmic#supported-hardware

**Comment by udellc** [comment]
Also, if hardware alternative is needed; I saw good reviews about this breakout:
https://www.multitech.com/brands/multiconnect-mdot

**Comment by WL-Richards** [comment]
Closing as this may no longer be necessary will reopen in the future.
The reasoning is that we will likely get a better range now that the Radios have been properly configured.
