### ISSUE TITLE
Add videos to Github Loom Documentation

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#64]
Please add the following video links and labels to a visible and appropriate place on our Github Documentation to help people get started, like new staff:
Loom Manager Walkthrough: https://media.oregonstate.edu/media/t/1_csq6zrae
Loom Hypnos Walkthrough: https://media.oregonstate.edu/media/t/1_7owroc4a
Hypnos Interrupts: https://media.oregonstate.edu/media/t/1_7hq18o2d

**Comment by WL-Richards** [comment]
README has been updated
