### ISSUE TITLE
i2c extender cable with 4-pin waterproof adapter on either side

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#65]
i2c extender cable with 4-pin waterproof adapter on either side
More details to follow

**Comment by udellc** [comment]
https://learn.sparkfun.com/tutorials/qwiic-differential-i2c-bus-extender-pca9615-hookup-guide/all
https://www.sparkfun.com/products/16988

We should make a send and receive endpoint attachment adapter for these

**Comment by WL-Richards** [comment]
@alexeiaburgos has completed this, closing
