### ISSUE TITLE
LTE Transmission Issue

### ISSUE THREAD

**Issue by AineeJames** [OPEnSLab-OSU/Loom-V4#67]
I have run into an odd issue where after around 40 transmissions using LTE, my device locks up and I have to reset it in order for it to work again. The issue started to occur once I added in all the necessary code for the adafruit VEML7700 breakout board. Measurements and connection work just fine, but like I said, it locks up after 40 transmissions using LTE.

Things I have tested:
- Removing sleep and disabling internet logging gets past 40 logs
- Removing VEML7700 code allows wifi logging to get past 40 transmissions

I am using a custom PCB using a hypnos v3_2, feather M0, SHT35, DS18B20, and VEML7700 for the lilypad project w/ the following code: https://github.com/OPEnSLab-OSU/Lilypad/tree/main/src/LilyPad4G

**Comment by WL-Richards** [comment]
Resolved by string refactor
