### ISSUE TITLE
MongoDB Tipping Bucket Calculate RainFall difference field

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#75]
In MongoDB, we need a standard way to calculate the rainfall tipping count difference from one sample to the next using the MongoDB custom field editor:
https://www.mongodb.com/docs/charts/calculated-fields/
https://www.mongodb.com/docs/manual/reference/operator/aggregation/subtract/#mongodb-expression-exp.-subtract

We want a custom field that subtracts the current sample tip count from the previous sample's tip count, and displays the result for that sample number. This is to show the accumulated rainfall for the duration of that sample. We only want the hardware to display the total number of tips for the lifetime of the device, but this isn't the most useful representation for our researchers. If we can do this in MongoDB charts, that would be great. See links above.

**Comment by WL-Richards** [comment]
This is now being handled in Loom by the TippingBucket class
