### ISSUE TITLE
SDI12 and GS3 Broken with string update

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#79]
We need to be able to use GS3 and other SDI 12 sensors - but we can't.
String overhaul messed up this functionality.

**Comment by WL-Richards** [comment]
This has been fixed in commit [55d2b5d](https://github.com/OPEnSLab-OSU/Loom-V4/commit/55d2b5d8fa8065986c55517851da7b8d74ca1e6d)
