### ISSUE TITLE
Max Subscribe Example to set Neopixel

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#8]
Test the Max Subscribe feature to set the Neopixel color levels from Max.
Include Example in the Max examples on the board profile.

**Comment by WL-Richards** [comment]
Wrriten and compiles

**Comment by udellc** [comment]
Tested neopixel Max example and Neopixel acutator example, neither work.
Neopixel connected to Wattson A2 port.

**Comment by udellc** [comment]
We'll need to test with hardware to sort this issues out I think. Hardware is in Gilmore Annex near WeatherChime equipment

**Comment by udellc** [comment]
Tested on Hardware
Raw non-Max example works!
Max example does not work.
Neopixel connected to port A2
Need to test this together, or @WL-Richards can use hardware on desk in lab to work things out.

**Comment by WL-Richards** [comment]
I think I may know why I can update it in a bit to test

**Comment by WL-Richards** [comment]
I believe the newest release will have resolved this please test, closing until further notice
