### ISSUE TITLE
Actuators should send their state when "publishing" or "Displaying" in json packet

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom-V4#9]
Actuators like Servo, Relay, Stepper, Neopixel should pack their status-state information in the JSON packet that would be logged, printed, or published. Good for redundant feedback on what Loom "thinks" the state of the actuator should be versus what is observed.

**Comment by WL-Richards** [comment]
This has been implemented but required a large re-work of how the actuators work, needs testing
